### ISSUE TITLE
pbs-spark-submit  should respect PBS_NUM_PPN

### ISSUE THREAD

**Issue by th3w4y** [tabaer/pbstools#1]
when pbs-spark-submit is spawning the workers it should respect the env PBS_NUM_PPN and set that to SPARK_WORKER_CORES accordingly.

currently this is not the case, in current implementation SPARK_WORKER_CORES always gets set to the maxim cores on the available machine

the current code will simply count all the cpus

```
        cpus = 0
        if ( os.path.exists("/proc/self/cpuset") ):
            cpusetfile = open("/proc/self/cpuset")
            cpuset = cpusetfile.read().rstrip("\n")
            cpusetfile.close()
        if ( os.path.exists("/dev/cpuset") ):
            cpusetroot = "/dev/cpuset"
        elif ( os.path.exists("/sys/fs/cgroup/cpuset") ):
            cpusetroot = "/sys/fs/cgroup/cpuset"
        if ( cpusetroot is not None and cpuset is not None ):
            cpusfile = None
            if ( os.path.exists(cpusetroot+cpuset+"/cpus") ):
                cpusfile = open(cpusetroot+cpuset+"/cpus")
            elif ( os.path.exists(cpusetroot+cpuset+"/cpuset.cpus") ):
                cpusfile = open(cpusetroot+cpuset+"/cpuset.cpus")
            if ( cpusfile is not None ):
                allcpus = cpusfile.read()
                cpusfile.close()
                for cgroup in allcpus.split(","):
                    cpurange = cgroup.split("-")
                    if ( len(cpurange)==1 ):
                        cpus += 1
                    elif ( len(cpurange)==2 ):
                        cpus += int(cpurange[1])-int(cpurange[0])+1

```

Assuming above code calculated cpu = MAX_CPU_AVAILABLE this is != 0
Then even if  PBS_NP is set in the environ nothing will happen

```
        if ( cpus==0 and "PBS_NP" in os.environ.keys() ):
            try:
                cpus = int(os.environ["PBS_NP"])
            except e,Exception:
                pass
        if ( cpus>0 ):
            os.environ["SPARK_WORKER_CORES"] = str(cpus)
            env["SPARK_WORKER_CORES"] = str(cpus)
```

I believe that the environment variable name is actually  PBS_NUM_PPN (number of processors per node) and SPARK_WORKER_CORES should be set to the min(cpus, os.environ["PBS_NUM_PPN"])

Usage of PBS_NP can lead to different results as PBS_NP = PBS_NUM_NODES \* PBS_NUM_PPN
and we should not spawn workers with total of PBS_NP on each node

Expected behaviour:
For example:

```
#PBS -l nodes=2:ppn=2
```

In this case pbs-spark-submit should behave like this:
- spawn 2 workers one per machine with 2 cores each

**Comment by tabaer** [comment]
If you have a patch for this, please send a pull request.  Unfortunately, it's likely going to be a while before I get to this otherwise.

**Comment by tabaer** [comment]
> Expected behaviour:
> For example:
> 
> #PBS -l nodes=2:ppn=2
> 
> In this case pbs-spark-submit should behave like this:
> 
> ```
> spawn 2 workers one per machine with 2 cores each
> ```

Honestly, that is not the behavior I would expect, so perhaps we have different expectations.  FWIW, the pbs-spark-submit man page states the following:

```
   --tpn <N> or --tasks-per-node <N> or -t <N>
          Launch  <N>  worker  tasks  per node.  The default is to use the
          :ppn= value from the job request.
```

**Comment by th3w4y** [comment]
@tabaer good hint about the tpn in that case i would have to set ton to 1 for my case 

For me personally it makes more sense to have one Spark worker per node using the specified number of cores in ppn (in the case that the node is shared with non Spark jobs)

**Comment by tabaer** [comment]
Also, the code in question is only used if you are using the Exec launcher, which you would only do on a single host.

**Comment by tabaer** [comment]
https://github.com/tabaer/pbstools/commit/ec032f9cd21799d8f0bc738d03d744ee048972a5 adds code for this.  However, as I said before, this is in the Exec launcher, which you would only use on a single host.

**Comment by th3w4y** [comment]
Thanks!
